### ISSUE TITLE
Errors with DBFolder

### ISSUE THREAD

**Issue by Eldresh** [polyipseity/obsidian-show-hidden-files#3]
Having this plugin enabled and turning on "Enable Javascript formulas" for DBFolder causes a spam of errors that sometimes crashes Obsidian. I'm admittedly not sure if this is something to report here or something to report there or just the plugins being completely incompatible, but felt I should report it anyways.

Attached screenshots are from a sandbox vault with default settings.

![image](https://github.com/polyipseity/obsidian-show-hidden-files/assets/32151068/3e1ebe47-48ed-4281-ad23-df31df451960)
![image](https://github.com/polyipseity/obsidian-show-hidden-files/assets/32151068/843b94ae-359b-4c8a-bcc1-0648b23968b0)

**Comment by polyipseity** [comment]
That is because DB Folder is loading the plugin JS files as formulas. It
can be fixed by:
1. Setting "Folder to read the templates" in DB Folder settings to
something other than the vault root; or
2. Disable "Show configuration folder" in Show Hidden Files settings; or
3. Filter out plugin JS files in "Showing rules" in Show Hidden Files
settings.

**Comment by Eldresh** [comment]
Ah, that makes sense. I didn't realize it would do that. Thanks for the quick reply.

**Comment by polyipseity** [comment]
Done in c932954c015bcd5b832bb3bd6bbdb9e6bce46571.
